-- This script was generated by the ERD tool in pgAdmin 4.
-- Please log an issue at https://github.com/pgadmin-org/pgadmin4/issues/new/choose if you find any bugs, including reproduction steps.
BEGIN;


CREATE TABLE IF NOT EXISTS public.area_atuacao
(
    area_atuacao_id serial NOT NULL,
    area_atuacao_nome character varying(30) COLLATE pg_catalog."default" NOT NULL,
    CONSTRAINT "PK_e3a20de2f6a8493d8e10a794fe4" PRIMARY KEY (area_atuacao_id)
);

CREATE TABLE IF NOT EXISTS public.etapa
(
    etapa_id serial NOT NULL,
    etapa_nome character varying(30) COLLATE pg_catalog."default" NOT NULL,
    etapa_descricao character varying(100) COLLATE pg_catalog."default" NOT NULL,
    etapa_data_inicio date NOT NULL,
    etapa_data_fim date NOT NULL,
    etapa_status boolean NOT NULL,
    proj_id integer,
    CONSTRAINT "PK_9fdc8b05f36ba0f1532efe19bf3" PRIMARY KEY (etapa_id)
);

CREATE TABLE IF NOT EXISTS public.migrations
(
    id serial NOT NULL,
    "timestamp" bigint NOT NULL,
    name character varying COLLATE pg_catalog."default" NOT NULL,
    CONSTRAINT "PK_8c82d7f526340ab734260ea46be" PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.projeto
(
    proj_id serial NOT NULL,
    proj_nome character varying(30) COLLATE pg_catalog."default" NOT NULL,
    proj_descricao character varying(100) COLLATE pg_catalog."default" NOT NULL,
    proj_area_atuacao character varying(50) COLLATE pg_catalog."default",
    proj_data_inicio date NOT NULL,
    proj_data_fim date NOT NULL,
    proj_status double precision NOT NULL,
    proj_excluido boolean NOT NULL,
    proj_inst_parceiras text[] COLLATE pg_catalog."default" DEFAULT '{}'::text[],
    proj_inst_financiadoras text[] COLLATE pg_catalog."default" DEFAULT '{}'::text[],
    proj_valor_total double precision,
    area_atuacao_id integer,
    proj_data_exclusao timestamp without time zone,
    CONSTRAINT "PK_2463d6724d037455d4d540ca422" PRIMARY KEY (proj_id)
);

CREATE TABLE IF NOT EXISTS public.rel_user_etapa
(
    user_id integer NOT NULL,
    etapa_id integer NOT NULL,
    CONSTRAINT "PK_05e8c7a6c5ec229b98aed2b1fb5" PRIMARY KEY (user_id, etapa_id)
);

CREATE TABLE IF NOT EXISTS public.rel_user_projeto
(
    user_id integer NOT NULL,
    proj_id integer NOT NULL,
    coordenador boolean NOT NULL DEFAULT false,
    CONSTRAINT "PK_69ebc6cd52c1248c050d978d128" PRIMARY KEY (user_id, proj_id)
);

CREATE TABLE IF NOT EXISTS public.rel_user_sub_tarefa
(
    user_id integer NOT NULL,
    subtarefa_id integer NOT NULL,
    CONSTRAINT "PK_881008b2aa033a811babfae3eaf" PRIMARY KEY (user_id, subtarefa_id)
);

CREATE TABLE IF NOT EXISTS public.rel_user_subtarefa
(
    user_id integer NOT NULL,
    subtarefa_id integer NOT NULL,
    CONSTRAINT "PK_bc74eb0894aa2cf503238af4cb2" PRIMARY KEY (user_id, subtarefa_id)
);

CREATE TABLE IF NOT EXISTS public.responsavel_user_tarefa
(
    user_id integer NOT NULL,
    tarefa_id integer NOT NULL,
    CONSTRAINT "PK_48e9b29bbda19730ec674ee8884" PRIMARY KEY (user_id, tarefa_id)
);

CREATE TABLE IF NOT EXISTS public.subtarefa
(
    subtarefa_id serial NOT NULL,
    subtarefa_nome character varying(30) COLLATE pg_catalog."default" NOT NULL,
    subtarefa_descricao character varying(100) COLLATE pg_catalog."default",
    subtarefa_data_inicio date,
    subtarefa_data_fim date,
    subtarefa_status boolean NOT NULL,
    tarefa_id integer,
    "usuariosUserId" integer,
    CONSTRAINT "PK_6ebde4c67af2a0d76bbc418b6d3" PRIMARY KEY (subtarefa_id)
);

CREATE TABLE IF NOT EXISTS public.tarefa
(
    tarefa_id serial NOT NULL,
    tarefa_nome character varying(30) COLLATE pg_catalog."default" NOT NULL,
    tarefa_descricao character varying(100) COLLATE pg_catalog."default" NOT NULL,
    tarefa_data_inicio date NOT NULL,
    tarefa_data_fim date NOT NULL,
    tarefa_status boolean NOT NULL,
    etapa_id integer,
    pontos_historias integer,
    CONSTRAINT "PK_1ead3a24db3072d39979c715ee5" PRIMARY KEY (tarefa_id)
);

CREATE TABLE IF NOT EXISTS public.tarefa_usuario
(
    tarefa_id integer NOT NULL,
    user_id integer NOT NULL,
    CONSTRAINT "PK_a8d56dc2284e4833443db4f821c" PRIMARY KEY (tarefa_id, user_id)
);

CREATE TABLE IF NOT EXISTS public.usuario
(
    user_id serial NOT NULL,
    user_nome character varying(30) COLLATE pg_catalog."default" NOT NULL,
    user_email character varying(100) COLLATE pg_catalog."default" NOT NULL,
    user_sobrenome character varying(30) COLLATE pg_catalog."default",
    user_foto character varying(255) COLLATE pg_catalog."default",
    registrado boolean NOT NULL DEFAULT true,
    CONSTRAINT "PK_b7d5ce144d689f786f30c5e39b6" PRIMARY KEY (user_id),
    CONSTRAINT "UQ_980c494756a12ab7a67b85dfecc" UNIQUE (user_email)
);

ALTER TABLE IF EXISTS public.etapa
    ADD CONSTRAINT "FK_6887ab820158c683ed660c5f2ff" FOREIGN KEY (proj_id)
    REFERENCES public.projeto (proj_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.projeto
    ADD CONSTRAINT "FK_483a5434446247c2410ac18aa6b" FOREIGN KEY (area_atuacao_id)
    REFERENCES public.area_atuacao (area_atuacao_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.rel_user_etapa
    ADD CONSTRAINT "FK_ad140b0dd54c60acecfbf32af36" FOREIGN KEY (user_id)
    REFERENCES public.usuario (user_id) MATCH SIMPLE
    ON UPDATE CASCADE
    ON DELETE CASCADE;
CREATE INDEX IF NOT EXISTS "IDX_ad140b0dd54c60acecfbf32af3"
    ON public.rel_user_etapa(user_id);


ALTER TABLE IF EXISTS public.rel_user_etapa
    ADD CONSTRAINT "FK_c4d3845ac77311db7dc044db7ba" FOREIGN KEY (etapa_id)
    REFERENCES public.etapa (etapa_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;
CREATE INDEX IF NOT EXISTS "IDX_c4d3845ac77311db7dc044db7b"
    ON public.rel_user_etapa(etapa_id);


ALTER TABLE IF EXISTS public.rel_user_projeto
    ADD CONSTRAINT "FK_0a47710c1294d090174c0e1d61a" FOREIGN KEY (proj_id)
    REFERENCES public.projeto (proj_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE;
CREATE INDEX IF NOT EXISTS "IDX_0a47710c1294d090174c0e1d61"
    ON public.rel_user_projeto(proj_id);


ALTER TABLE IF EXISTS public.rel_user_projeto
    ADD CONSTRAINT "FK_cb6869d2ca20c7e2c92e028a1df" FOREIGN KEY (user_id)
    REFERENCES public.usuario (user_id) MATCH SIMPLE
    ON UPDATE CASCADE
    ON DELETE CASCADE;
CREATE INDEX IF NOT EXISTS "IDX_cb6869d2ca20c7e2c92e028a1d"
    ON public.rel_user_projeto(user_id);


ALTER TABLE IF EXISTS public.rel_user_subtarefa
    ADD CONSTRAINT "FK_74928992ccf50e7f6365b4f9e20" FOREIGN KEY (subtarefa_id)
    REFERENCES public.subtarefa (subtarefa_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE;
CREATE INDEX IF NOT EXISTS "IDX_74928992ccf50e7f6365b4f9e2"
    ON public.rel_user_subtarefa(subtarefa_id);


ALTER TABLE IF EXISTS public.rel_user_subtarefa
    ADD CONSTRAINT "FK_ad6dda6545ea04a3dd32988b264" FOREIGN KEY (user_id)
    REFERENCES public.usuario (user_id) MATCH SIMPLE
    ON UPDATE CASCADE
    ON DELETE CASCADE;
CREATE INDEX IF NOT EXISTS "IDX_ad6dda6545ea04a3dd32988b26"
    ON public.rel_user_subtarefa(user_id);


ALTER TABLE IF EXISTS public.responsavel_user_tarefa
    ADD CONSTRAINT "FK_22f46febaa012ec54133e9c0fce" FOREIGN KEY (tarefa_id)
    REFERENCES public.tarefa (tarefa_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;
CREATE INDEX IF NOT EXISTS "IDX_22f46febaa012ec54133e9c0fc"
    ON public.responsavel_user_tarefa(tarefa_id);


ALTER TABLE IF EXISTS public.responsavel_user_tarefa
    ADD CONSTRAINT "FK_ebf940eb471b976a873b82c877f" FOREIGN KEY (user_id)
    REFERENCES public.usuario (user_id) MATCH SIMPLE
    ON UPDATE CASCADE
    ON DELETE CASCADE;
CREATE INDEX IF NOT EXISTS "IDX_ebf940eb471b976a873b82c877"
    ON public.responsavel_user_tarefa(user_id);


ALTER TABLE IF EXISTS public.subtarefa
    ADD CONSTRAINT "FK_5739187223782939949f38ed55b" FOREIGN KEY ("usuariosUserId")
    REFERENCES public.usuario (user_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE;


ALTER TABLE IF EXISTS public.subtarefa
    ADD CONSTRAINT "FK_5f29a5cece71352930ba5e475a6" FOREIGN KEY (tarefa_id)
    REFERENCES public.tarefa (tarefa_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE;


ALTER TABLE IF EXISTS public.tarefa
    ADD CONSTRAINT "FK_bb32d16f456359987194177a07a" FOREIGN KEY (etapa_id)
    REFERENCES public.etapa (etapa_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.tarefa_usuario
    ADD CONSTRAINT "FK_091073d26143612e7e29b86986f" FOREIGN KEY (user_id)
    REFERENCES public.usuario (user_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;
CREATE INDEX IF NOT EXISTS "IDX_091073d26143612e7e29b86986"
    ON public.tarefa_usuario(user_id);


ALTER TABLE IF EXISTS public.tarefa_usuario
    ADD CONSTRAINT "FK_d3358aea84b2eb125ceb48648ae" FOREIGN KEY (tarefa_id)
    REFERENCES public.tarefa (tarefa_id) MATCH SIMPLE
    ON UPDATE CASCADE
    ON DELETE CASCADE;
CREATE INDEX IF NOT EXISTS "IDX_d3358aea84b2eb125ceb48648a"
    ON public.tarefa_usuario(tarefa_id);

END;